/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TillaggstjansterRouteImport } from './routes/tillaggstjanster'
import { Route as RegistreraRouteImport } from './routes/registrera'
import { Route as LoggaInRouteImport } from './routes/logga-in'
import { Route as HurDetFunkarRouteImport } from './routes/hur-det-funkar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SaljareSkapaAnnonsRouteImport } from './routes/saljare.skapa-annons'
import { Route as SaljareMinaAnnonserRouteImport } from './routes/saljare.mina-annonser'
import { Route as SaljareIntressenterRouteImport } from './routes/saljare.intressenter'
import { Route as SaljareAffarerRouteImport } from './routes/saljare.affarer'
import { Route as KopareProfilRouteImport } from './routes/kopare.profil'
import { Route as KopareFavoriterRouteImport } from './routes/kopare.favoriter'
import { Route as KopareBevakningarRouteImport } from './routes/kopare.bevakningar'
import { Route as KopareAffarerRouteImport } from './routes/kopare.affarer'
import { Route as AnnonsIdRouteImport } from './routes/annons.$id'
import { Route as AffarIdRouteImport } from './routes/affar.$id'

const TillaggstjansterRoute = TillaggstjansterRouteImport.update({
  id: '/tillaggstjanster',
  path: '/tillaggstjanster',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistreraRoute = RegistreraRouteImport.update({
  id: '/registrera',
  path: '/registrera',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggaInRoute = LoggaInRouteImport.update({
  id: '/logga-in',
  path: '/logga-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HurDetFunkarRoute = HurDetFunkarRouteImport.update({
  id: '/hur-det-funkar',
  path: '/hur-det-funkar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaljareSkapaAnnonsRoute = SaljareSkapaAnnonsRouteImport.update({
  id: '/saljare/skapa-annons',
  path: '/saljare/skapa-annons',
  getParentRoute: () => rootRouteImport,
} as any)
const SaljareMinaAnnonserRoute = SaljareMinaAnnonserRouteImport.update({
  id: '/saljare/mina-annonser',
  path: '/saljare/mina-annonser',
  getParentRoute: () => rootRouteImport,
} as any)
const SaljareIntressenterRoute = SaljareIntressenterRouteImport.update({
  id: '/saljare/intressenter',
  path: '/saljare/intressenter',
  getParentRoute: () => rootRouteImport,
} as any)
const SaljareAffarerRoute = SaljareAffarerRouteImport.update({
  id: '/saljare/affarer',
  path: '/saljare/affarer',
  getParentRoute: () => rootRouteImport,
} as any)
const KopareProfilRoute = KopareProfilRouteImport.update({
  id: '/kopare/profil',
  path: '/kopare/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const KopareFavoriterRoute = KopareFavoriterRouteImport.update({
  id: '/kopare/favoriter',
  path: '/kopare/favoriter',
  getParentRoute: () => rootRouteImport,
} as any)
const KopareBevakningarRoute = KopareBevakningarRouteImport.update({
  id: '/kopare/bevakningar',
  path: '/kopare/bevakningar',
  getParentRoute: () => rootRouteImport,
} as any)
const KopareAffarerRoute = KopareAffarerRouteImport.update({
  id: '/kopare/affarer',
  path: '/kopare/affarer',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnonsIdRoute = AnnonsIdRouteImport.update({
  id: '/annons/$id',
  path: '/annons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AffarIdRoute = AffarIdRouteImport.update({
  id: '/affar/$id',
  path: '/affar/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/hur-det-funkar': typeof HurDetFunkarRoute
  '/logga-in': typeof LoggaInRoute
  '/registrera': typeof RegistreraRoute
  '/tillaggstjanster': typeof TillaggstjansterRoute
  '/affar/$id': typeof AffarIdRoute
  '/annons/$id': typeof AnnonsIdRoute
  '/kopare/affarer': typeof KopareAffarerRoute
  '/kopare/bevakningar': typeof KopareBevakningarRoute
  '/kopare/favoriter': typeof KopareFavoriterRoute
  '/kopare/profil': typeof KopareProfilRoute
  '/saljare/affarer': typeof SaljareAffarerRoute
  '/saljare/intressenter': typeof SaljareIntressenterRoute
  '/saljare/mina-annonser': typeof SaljareMinaAnnonserRoute
  '/saljare/skapa-annons': typeof SaljareSkapaAnnonsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/hur-det-funkar': typeof HurDetFunkarRoute
  '/logga-in': typeof LoggaInRoute
  '/registrera': typeof RegistreraRoute
  '/tillaggstjanster': typeof TillaggstjansterRoute
  '/affar/$id': typeof AffarIdRoute
  '/annons/$id': typeof AnnonsIdRoute
  '/kopare/affarer': typeof KopareAffarerRoute
  '/kopare/bevakningar': typeof KopareBevakningarRoute
  '/kopare/favoriter': typeof KopareFavoriterRoute
  '/kopare/profil': typeof KopareProfilRoute
  '/saljare/affarer': typeof SaljareAffarerRoute
  '/saljare/intressenter': typeof SaljareIntressenterRoute
  '/saljare/mina-annonser': typeof SaljareMinaAnnonserRoute
  '/saljare/skapa-annons': typeof SaljareSkapaAnnonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/hur-det-funkar': typeof HurDetFunkarRoute
  '/logga-in': typeof LoggaInRoute
  '/registrera': typeof RegistreraRoute
  '/tillaggstjanster': typeof TillaggstjansterRoute
  '/affar/$id': typeof AffarIdRoute
  '/annons/$id': typeof AnnonsIdRoute
  '/kopare/affarer': typeof KopareAffarerRoute
  '/kopare/bevakningar': typeof KopareBevakningarRoute
  '/kopare/favoriter': typeof KopareFavoriterRoute
  '/kopare/profil': typeof KopareProfilRoute
  '/saljare/affarer': typeof SaljareAffarerRoute
  '/saljare/intressenter': typeof SaljareIntressenterRoute
  '/saljare/mina-annonser': typeof SaljareMinaAnnonserRoute
  '/saljare/skapa-annons': typeof SaljareSkapaAnnonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/hur-det-funkar'
    | '/logga-in'
    | '/registrera'
    | '/tillaggstjanster'
    | '/affar/$id'
    | '/annons/$id'
    | '/kopare/affarer'
    | '/kopare/bevakningar'
    | '/kopare/favoriter'
    | '/kopare/profil'
    | '/saljare/affarer'
    | '/saljare/intressenter'
    | '/saljare/mina-annonser'
    | '/saljare/skapa-annons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/hur-det-funkar'
    | '/logga-in'
    | '/registrera'
    | '/tillaggstjanster'
    | '/affar/$id'
    | '/annons/$id'
    | '/kopare/affarer'
    | '/kopare/bevakningar'
    | '/kopare/favoriter'
    | '/kopare/profil'
    | '/saljare/affarer'
    | '/saljare/intressenter'
    | '/saljare/mina-annonser'
    | '/saljare/skapa-annons'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/hur-det-funkar'
    | '/logga-in'
    | '/registrera'
    | '/tillaggstjanster'
    | '/affar/$id'
    | '/annons/$id'
    | '/kopare/affarer'
    | '/kopare/bevakningar'
    | '/kopare/favoriter'
    | '/kopare/profil'
    | '/saljare/affarer'
    | '/saljare/intressenter'
    | '/saljare/mina-annonser'
    | '/saljare/skapa-annons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HurDetFunkarRoute: typeof HurDetFunkarRoute
  LoggaInRoute: typeof LoggaInRoute
  RegistreraRoute: typeof RegistreraRoute
  TillaggstjansterRoute: typeof TillaggstjansterRoute
  AffarIdRoute: typeof AffarIdRoute
  AnnonsIdRoute: typeof AnnonsIdRoute
  KopareAffarerRoute: typeof KopareAffarerRoute
  KopareBevakningarRoute: typeof KopareBevakningarRoute
  KopareFavoriterRoute: typeof KopareFavoriterRoute
  KopareProfilRoute: typeof KopareProfilRoute
  SaljareAffarerRoute: typeof SaljareAffarerRoute
  SaljareIntressenterRoute: typeof SaljareIntressenterRoute
  SaljareMinaAnnonserRoute: typeof SaljareMinaAnnonserRoute
  SaljareSkapaAnnonsRoute: typeof SaljareSkapaAnnonsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tillaggstjanster': {
      id: '/tillaggstjanster'
      path: '/tillaggstjanster'
      fullPath: '/tillaggstjanster'
      preLoaderRoute: typeof TillaggstjansterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrera': {
      id: '/registrera'
      path: '/registrera'
      fullPath: '/registrera'
      preLoaderRoute: typeof RegistreraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logga-in': {
      id: '/logga-in'
      path: '/logga-in'
      fullPath: '/logga-in'
      preLoaderRoute: typeof LoggaInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hur-det-funkar': {
      id: '/hur-det-funkar'
      path: '/hur-det-funkar'
      fullPath: '/hur-det-funkar'
      preLoaderRoute: typeof HurDetFunkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saljare/skapa-annons': {
      id: '/saljare/skapa-annons'
      path: '/saljare/skapa-annons'
      fullPath: '/saljare/skapa-annons'
      preLoaderRoute: typeof SaljareSkapaAnnonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saljare/mina-annonser': {
      id: '/saljare/mina-annonser'
      path: '/saljare/mina-annonser'
      fullPath: '/saljare/mina-annonser'
      preLoaderRoute: typeof SaljareMinaAnnonserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saljare/intressenter': {
      id: '/saljare/intressenter'
      path: '/saljare/intressenter'
      fullPath: '/saljare/intressenter'
      preLoaderRoute: typeof SaljareIntressenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saljare/affarer': {
      id: '/saljare/affarer'
      path: '/saljare/affarer'
      fullPath: '/saljare/affarer'
      preLoaderRoute: typeof SaljareAffarerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopare/profil': {
      id: '/kopare/profil'
      path: '/kopare/profil'
      fullPath: '/kopare/profil'
      preLoaderRoute: typeof KopareProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopare/favoriter': {
      id: '/kopare/favoriter'
      path: '/kopare/favoriter'
      fullPath: '/kopare/favoriter'
      preLoaderRoute: typeof KopareFavoriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopare/bevakningar': {
      id: '/kopare/bevakningar'
      path: '/kopare/bevakningar'
      fullPath: '/kopare/bevakningar'
      preLoaderRoute: typeof KopareBevakningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopare/affarer': {
      id: '/kopare/affarer'
      path: '/kopare/affarer'
      fullPath: '/kopare/affarer'
      preLoaderRoute: typeof KopareAffarerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annons/$id': {
      id: '/annons/$id'
      path: '/annons/$id'
      fullPath: '/annons/$id'
      preLoaderRoute: typeof AnnonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affar/$id': {
      id: '/affar/$id'
      path: '/affar/$id'
      fullPath: '/affar/$id'
      preLoaderRoute: typeof AffarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HurDetFunkarRoute: HurDetFunkarRoute,
  LoggaInRoute: LoggaInRoute,
  RegistreraRoute: RegistreraRoute,
  TillaggstjansterRoute: TillaggstjansterRoute,
  AffarIdRoute: AffarIdRoute,
  AnnonsIdRoute: AnnonsIdRoute,
  KopareAffarerRoute: KopareAffarerRoute,
  KopareBevakningarRoute: KopareBevakningarRoute,
  KopareFavoriterRoute: KopareFavoriterRoute,
  KopareProfilRoute: KopareProfilRoute,
  SaljareAffarerRoute: SaljareAffarerRoute,
  SaljareIntressenterRoute: SaljareIntressenterRoute,
  SaljareMinaAnnonserRoute: SaljareMinaAnnonserRoute,
  SaljareSkapaAnnonsRoute: SaljareSkapaAnnonsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
