/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillkorRouteImport } from './routes/villkor'
import { Route as TillaggstjansterRouteImport } from './routes/tillaggstjanster'
import { Route as RegistreraRouteImport } from './routes/registrera'
import { Route as OversiktRouteImport } from './routes/oversikt'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LokalerRouteImport } from './routes/lokaler'
import { Route as LoggaInRouteImport } from './routes/logga-in'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as HurDetFunkarRouteImport } from './routes/hur-det-funkar'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GeorgeIndexRouteImport } from './routes/george.index'
import { Route as SaljareSkapaAnnonsRouteImport } from './routes/saljare.skapa-annons'
import { Route as SaljareMinaAnnonserRouteImport } from './routes/saljare.mina-annonser'
import { Route as SaljareIntressenterRouteImport } from './routes/saljare.intressenter'
import { Route as SaljareAnnonsInskickadRouteImport } from './routes/saljare.annons-inskickad'
import { Route as SaljareAffarerRouteImport } from './routes/saljare.affarer'
import { Route as KopareProfilRouteImport } from './routes/kopare.profil'
import { Route as KopareJamforRouteImport } from './routes/kopare.jamfor'
import { Route as KopareFavoriterRouteImport } from './routes/kopare.favoriter'
import { Route as KopareBevakningarRouteImport } from './routes/kopare.bevakningar'
import { Route as KopareAffarerRouteImport } from './routes/kopare.affarer'
import { Route as GeorgeHyresvardRouteImport } from './routes/george.hyresvard'
import { Route as GeorgeFakturorRouteImport } from './routes/george.fakturor'
import { Route as GeorgeAnvandareRouteImport } from './routes/george.anvandare'
import { Route as GeorgeAnnonserRouteImport } from './routes/george.annonser'
import { Route as GeorgeAffarerRouteImport } from './routes/george.affarer'
import { Route as AnnonsIdRouteImport } from './routes/annons.$id'
import { Route as AffarIdRouteImport } from './routes/affar.$id'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as GeorgeAnnonserIndexRouteImport } from './routes/george.annonser.index'
import { Route as SaljareAnnonsIdRouteImport } from './routes/saljare.annons.$id'
import { Route as GeorgeAnnonserIdRouteImport } from './routes/george.annonser.$id'
import { Route as GeorgeAnnonsFlodeIdRouteImport } from './routes/george.annons-flode.$id'
import { Route as AnnonsIdIntresseRouteImport } from './routes/annons.$id.intresse'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const VillkorRoute = VillkorRouteImport.update({
  id: '/villkor',
  path: '/villkor',
  getParentRoute: () => rootRouteImport,
} as any)
const TillaggstjansterRoute = TillaggstjansterRouteImport.update({
  id: '/tillaggstjanster',
  path: '/tillaggstjanster',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistreraRoute = RegistreraRouteImport.update({
  id: '/registrera',
  path: '/registrera',
  getParentRoute: () => rootRouteImport,
} as any)
const OversiktRoute = OversiktRouteImport.update({
  id: '/oversikt',
  path: '/oversikt',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LokalerRoute = LokalerRouteImport.update({
  id: '/lokaler',
  path: '/lokaler',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggaInRoute = LoggaInRouteImport.update({
  id: '/logga-in',
  path: '/logga-in',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const HurDetFunkarRoute = HurDetFunkarRouteImport.update({
  id: '/hur-det-funkar',
  path: '/hur-det-funkar',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeorgeIndexRoute = GeorgeIndexRouteImport.update({
  id: '/george/',
  path: '/george/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaljareSkapaAnnonsRoute = SaljareSkapaAnnonsRouteImport.update({
  id: '/saljare/skapa-annons',
  path: '/saljare/skapa-annons',
  getParentRoute: () => rootRouteImport,
} as any)
const SaljareMinaAnnonserRoute = SaljareMinaAnnonserRouteImport.update({
  id: '/saljare/mina-annonser',
  path: '/saljare/mina-annonser',
  getParentRoute: () => rootRouteImport,
} as any)
const SaljareIntressenterRoute = SaljareIntressenterRouteImport.update({
  id: '/saljare/intressenter',
  path: '/saljare/intressenter',
  getParentRoute: () => rootRouteImport,
} as any)
const SaljareAnnonsInskickadRoute = SaljareAnnonsInskickadRouteImport.update({
  id: '/saljare/annons-inskickad',
  path: '/saljare/annons-inskickad',
  getParentRoute: () => rootRouteImport,
} as any)
const SaljareAffarerRoute = SaljareAffarerRouteImport.update({
  id: '/saljare/affarer',
  path: '/saljare/affarer',
  getParentRoute: () => rootRouteImport,
} as any)
const KopareProfilRoute = KopareProfilRouteImport.update({
  id: '/kopare/profil',
  path: '/kopare/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const KopareJamforRoute = KopareJamforRouteImport.update({
  id: '/kopare/jamfor',
  path: '/kopare/jamfor',
  getParentRoute: () => rootRouteImport,
} as any)
const KopareFavoriterRoute = KopareFavoriterRouteImport.update({
  id: '/kopare/favoriter',
  path: '/kopare/favoriter',
  getParentRoute: () => rootRouteImport,
} as any)
const KopareBevakningarRoute = KopareBevakningarRouteImport.update({
  id: '/kopare/bevakningar',
  path: '/kopare/bevakningar',
  getParentRoute: () => rootRouteImport,
} as any)
const KopareAffarerRoute = KopareAffarerRouteImport.update({
  id: '/kopare/affarer',
  path: '/kopare/affarer',
  getParentRoute: () => rootRouteImport,
} as any)
const GeorgeHyresvardRoute = GeorgeHyresvardRouteImport.update({
  id: '/george/hyresvard',
  path: '/george/hyresvard',
  getParentRoute: () => rootRouteImport,
} as any)
const GeorgeFakturorRoute = GeorgeFakturorRouteImport.update({
  id: '/george/fakturor',
  path: '/george/fakturor',
  getParentRoute: () => rootRouteImport,
} as any)
const GeorgeAnvandareRoute = GeorgeAnvandareRouteImport.update({
  id: '/george/anvandare',
  path: '/george/anvandare',
  getParentRoute: () => rootRouteImport,
} as any)
const GeorgeAnnonserRoute = GeorgeAnnonserRouteImport.update({
  id: '/george/annonser',
  path: '/george/annonser',
  getParentRoute: () => rootRouteImport,
} as any)
const GeorgeAffarerRoute = GeorgeAffarerRouteImport.update({
  id: '/george/affarer',
  path: '/george/affarer',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnonsIdRoute = AnnonsIdRouteImport.update({
  id: '/annons/$id',
  path: '/annons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AffarIdRoute = AffarIdRouteImport.update({
  id: '/affar/$id',
  path: '/affar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const GeorgeAnnonserIndexRoute = GeorgeAnnonserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GeorgeAnnonserRoute,
} as any)
const SaljareAnnonsIdRoute = SaljareAnnonsIdRouteImport.update({
  id: '/saljare/annons/$id',
  path: '/saljare/annons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GeorgeAnnonserIdRoute = GeorgeAnnonserIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GeorgeAnnonserRoute,
} as any)
const GeorgeAnnonsFlodeIdRoute = GeorgeAnnonsFlodeIdRouteImport.update({
  id: '/george/annons-flode/$id',
  path: '/george/annons-flode/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnonsIdIntresseRoute = AnnonsIdIntresseRouteImport.update({
  id: '/intresse',
  path: '/intresse',
  getParentRoute: () => AnnonsIdRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/hur-det-funkar': typeof HurDetFunkarRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/logga-in': typeof LoggaInRoute
  '/lokaler': typeof LokalerRoute
  '/mcp': typeof McpRoute
  '/om-oss': typeof OmOssRoute
  '/onboarding': typeof OnboardingRoute
  '/oversikt': typeof OversiktRoute
  '/registrera': typeof RegistreraRoute
  '/tillaggstjanster': typeof TillaggstjansterRoute
  '/villkor': typeof VillkorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/affar/$id': typeof AffarIdRoute
  '/annons/$id': typeof AnnonsIdRouteWithChildren
  '/george/affarer': typeof GeorgeAffarerRoute
  '/george/annonser': typeof GeorgeAnnonserRouteWithChildren
  '/george/anvandare': typeof GeorgeAnvandareRoute
  '/george/fakturor': typeof GeorgeFakturorRoute
  '/george/hyresvard': typeof GeorgeHyresvardRoute
  '/kopare/affarer': typeof KopareAffarerRoute
  '/kopare/bevakningar': typeof KopareBevakningarRoute
  '/kopare/favoriter': typeof KopareFavoriterRoute
  '/kopare/jamfor': typeof KopareJamforRoute
  '/kopare/profil': typeof KopareProfilRoute
  '/saljare/affarer': typeof SaljareAffarerRoute
  '/saljare/annons-inskickad': typeof SaljareAnnonsInskickadRoute
  '/saljare/intressenter': typeof SaljareIntressenterRoute
  '/saljare/mina-annonser': typeof SaljareMinaAnnonserRoute
  '/saljare/skapa-annons': typeof SaljareSkapaAnnonsRoute
  '/george/': typeof GeorgeIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/annons/$id/intresse': typeof AnnonsIdIntresseRoute
  '/george/annons-flode/$id': typeof GeorgeAnnonsFlodeIdRoute
  '/george/annonser/$id': typeof GeorgeAnnonserIdRoute
  '/saljare/annons/$id': typeof SaljareAnnonsIdRoute
  '/george/annonser/': typeof GeorgeAnnonserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/hur-det-funkar': typeof HurDetFunkarRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/logga-in': typeof LoggaInRoute
  '/lokaler': typeof LokalerRoute
  '/mcp': typeof McpRoute
  '/om-oss': typeof OmOssRoute
  '/onboarding': typeof OnboardingRoute
  '/oversikt': typeof OversiktRoute
  '/registrera': typeof RegistreraRoute
  '/tillaggstjanster': typeof TillaggstjansterRoute
  '/villkor': typeof VillkorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/affar/$id': typeof AffarIdRoute
  '/annons/$id': typeof AnnonsIdRouteWithChildren
  '/george/affarer': typeof GeorgeAffarerRoute
  '/george/anvandare': typeof GeorgeAnvandareRoute
  '/george/fakturor': typeof GeorgeFakturorRoute
  '/george/hyresvard': typeof GeorgeHyresvardRoute
  '/kopare/affarer': typeof KopareAffarerRoute
  '/kopare/bevakningar': typeof KopareBevakningarRoute
  '/kopare/favoriter': typeof KopareFavoriterRoute
  '/kopare/jamfor': typeof KopareJamforRoute
  '/kopare/profil': typeof KopareProfilRoute
  '/saljare/affarer': typeof SaljareAffarerRoute
  '/saljare/annons-inskickad': typeof SaljareAnnonsInskickadRoute
  '/saljare/intressenter': typeof SaljareIntressenterRoute
  '/saljare/mina-annonser': typeof SaljareMinaAnnonserRoute
  '/saljare/skapa-annons': typeof SaljareSkapaAnnonsRoute
  '/george': typeof GeorgeIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/annons/$id/intresse': typeof AnnonsIdIntresseRoute
  '/george/annons-flode/$id': typeof GeorgeAnnonsFlodeIdRoute
  '/george/annonser/$id': typeof GeorgeAnnonserIdRoute
  '/saljare/annons/$id': typeof SaljareAnnonsIdRoute
  '/george/annonser': typeof GeorgeAnnonserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/hur-det-funkar': typeof HurDetFunkarRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/logga-in': typeof LoggaInRoute
  '/lokaler': typeof LokalerRoute
  '/mcp': typeof McpRoute
  '/om-oss': typeof OmOssRoute
  '/onboarding': typeof OnboardingRoute
  '/oversikt': typeof OversiktRoute
  '/registrera': typeof RegistreraRoute
  '/tillaggstjanster': typeof TillaggstjansterRoute
  '/villkor': typeof VillkorRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/affar/$id': typeof AffarIdRoute
  '/annons/$id': typeof AnnonsIdRouteWithChildren
  '/george/affarer': typeof GeorgeAffarerRoute
  '/george/annonser': typeof GeorgeAnnonserRouteWithChildren
  '/george/anvandare': typeof GeorgeAnvandareRoute
  '/george/fakturor': typeof GeorgeFakturorRoute
  '/george/hyresvard': typeof GeorgeHyresvardRoute
  '/kopare/affarer': typeof KopareAffarerRoute
  '/kopare/bevakningar': typeof KopareBevakningarRoute
  '/kopare/favoriter': typeof KopareFavoriterRoute
  '/kopare/jamfor': typeof KopareJamforRoute
  '/kopare/profil': typeof KopareProfilRoute
  '/saljare/affarer': typeof SaljareAffarerRoute
  '/saljare/annons-inskickad': typeof SaljareAnnonsInskickadRoute
  '/saljare/intressenter': typeof SaljareIntressenterRoute
  '/saljare/mina-annonser': typeof SaljareMinaAnnonserRoute
  '/saljare/skapa-annons': typeof SaljareSkapaAnnonsRoute
  '/george/': typeof GeorgeIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/annons/$id/intresse': typeof AnnonsIdIntresseRoute
  '/george/annons-flode/$id': typeof GeorgeAnnonsFlodeIdRoute
  '/george/annonser/$id': typeof GeorgeAnnonserIdRoute
  '/saljare/annons/$id': typeof SaljareAnnonsIdRoute
  '/george/annonser/': typeof GeorgeAnnonserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/dashboard'
    | '/faq'
    | '/hur-det-funkar'
    | '/integritetspolicy'
    | '/kontakt'
    | '/logga-in'
    | '/lokaler'
    | '/mcp'
    | '/om-oss'
    | '/onboarding'
    | '/oversikt'
    | '/registrera'
    | '/tillaggstjanster'
    | '/villkor'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/affar/$id'
    | '/annons/$id'
    | '/george/affarer'
    | '/george/annonser'
    | '/george/anvandare'
    | '/george/fakturor'
    | '/george/hyresvard'
    | '/kopare/affarer'
    | '/kopare/bevakningar'
    | '/kopare/favoriter'
    | '/kopare/jamfor'
    | '/kopare/profil'
    | '/saljare/affarer'
    | '/saljare/annons-inskickad'
    | '/saljare/intressenter'
    | '/saljare/mina-annonser'
    | '/saljare/skapa-annons'
    | '/george/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/annons/$id/intresse'
    | '/george/annons-flode/$id'
    | '/george/annonser/$id'
    | '/saljare/annons/$id'
    | '/george/annonser/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/dashboard'
    | '/faq'
    | '/hur-det-funkar'
    | '/integritetspolicy'
    | '/kontakt'
    | '/logga-in'
    | '/lokaler'
    | '/mcp'
    | '/om-oss'
    | '/onboarding'
    | '/oversikt'
    | '/registrera'
    | '/tillaggstjanster'
    | '/villkor'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/affar/$id'
    | '/annons/$id'
    | '/george/affarer'
    | '/george/anvandare'
    | '/george/fakturor'
    | '/george/hyresvard'
    | '/kopare/affarer'
    | '/kopare/bevakningar'
    | '/kopare/favoriter'
    | '/kopare/jamfor'
    | '/kopare/profil'
    | '/saljare/affarer'
    | '/saljare/annons-inskickad'
    | '/saljare/intressenter'
    | '/saljare/mina-annonser'
    | '/saljare/skapa-annons'
    | '/george'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/annons/$id/intresse'
    | '/george/annons-flode/$id'
    | '/george/annonser/$id'
    | '/saljare/annons/$id'
    | '/george/annonser'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/dashboard'
    | '/faq'
    | '/hur-det-funkar'
    | '/integritetspolicy'
    | '/kontakt'
    | '/logga-in'
    | '/lokaler'
    | '/mcp'
    | '/om-oss'
    | '/onboarding'
    | '/oversikt'
    | '/registrera'
    | '/tillaggstjanster'
    | '/villkor'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/affar/$id'
    | '/annons/$id'
    | '/george/affarer'
    | '/george/annonser'
    | '/george/anvandare'
    | '/george/fakturor'
    | '/george/hyresvard'
    | '/kopare/affarer'
    | '/kopare/bevakningar'
    | '/kopare/favoriter'
    | '/kopare/jamfor'
    | '/kopare/profil'
    | '/saljare/affarer'
    | '/saljare/annons-inskickad'
    | '/saljare/intressenter'
    | '/saljare/mina-annonser'
    | '/saljare/skapa-annons'
    | '/george/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/annons/$id/intresse'
    | '/george/annons-flode/$id'
    | '/george/annonser/$id'
    | '/saljare/annons/$id'
    | '/george/annonser/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  HurDetFunkarRoute: typeof HurDetFunkarRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  KontaktRoute: typeof KontaktRoute
  LoggaInRoute: typeof LoggaInRoute
  LokalerRoute: typeof LokalerRoute
  McpRoute: typeof McpRoute
  OmOssRoute: typeof OmOssRoute
  OnboardingRoute: typeof OnboardingRoute
  OversiktRoute: typeof OversiktRoute
  RegistreraRoute: typeof RegistreraRoute
  TillaggstjansterRoute: typeof TillaggstjansterRoute
  VillkorRoute: typeof VillkorRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AffarIdRoute: typeof AffarIdRoute
  AnnonsIdRoute: typeof AnnonsIdRouteWithChildren
  GeorgeAffarerRoute: typeof GeorgeAffarerRoute
  GeorgeAnnonserRoute: typeof GeorgeAnnonserRouteWithChildren
  GeorgeAnvandareRoute: typeof GeorgeAnvandareRoute
  GeorgeFakturorRoute: typeof GeorgeFakturorRoute
  GeorgeHyresvardRoute: typeof GeorgeHyresvardRoute
  KopareAffarerRoute: typeof KopareAffarerRoute
  KopareBevakningarRoute: typeof KopareBevakningarRoute
  KopareFavoriterRoute: typeof KopareFavoriterRoute
  KopareJamforRoute: typeof KopareJamforRoute
  KopareProfilRoute: typeof KopareProfilRoute
  SaljareAffarerRoute: typeof SaljareAffarerRoute
  SaljareAnnonsInskickadRoute: typeof SaljareAnnonsInskickadRoute
  SaljareIntressenterRoute: typeof SaljareIntressenterRoute
  SaljareMinaAnnonserRoute: typeof SaljareMinaAnnonserRoute
  SaljareSkapaAnnonsRoute: typeof SaljareSkapaAnnonsRoute
  GeorgeIndexRoute: typeof GeorgeIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  GeorgeAnnonsFlodeIdRoute: typeof GeorgeAnnonsFlodeIdRoute
  SaljareAnnonsIdRoute: typeof SaljareAnnonsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villkor': {
      id: '/villkor'
      path: '/villkor'
      fullPath: '/villkor'
      preLoaderRoute: typeof VillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tillaggstjanster': {
      id: '/tillaggstjanster'
      path: '/tillaggstjanster'
      fullPath: '/tillaggstjanster'
      preLoaderRoute: typeof TillaggstjansterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrera': {
      id: '/registrera'
      path: '/registrera'
      fullPath: '/registrera'
      preLoaderRoute: typeof RegistreraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oversikt': {
      id: '/oversikt'
      path: '/oversikt'
      fullPath: '/oversikt'
      preLoaderRoute: typeof OversiktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lokaler': {
      id: '/lokaler'
      path: '/lokaler'
      fullPath: '/lokaler'
      preLoaderRoute: typeof LokalerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logga-in': {
      id: '/logga-in'
      path: '/logga-in'
      fullPath: '/logga-in'
      preLoaderRoute: typeof LoggaInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hur-det-funkar': {
      id: '/hur-det-funkar'
      path: '/hur-det-funkar'
      fullPath: '/hur-det-funkar'
      preLoaderRoute: typeof HurDetFunkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/george/': {
      id: '/george/'
      path: '/george'
      fullPath: '/george/'
      preLoaderRoute: typeof GeorgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saljare/skapa-annons': {
      id: '/saljare/skapa-annons'
      path: '/saljare/skapa-annons'
      fullPath: '/saljare/skapa-annons'
      preLoaderRoute: typeof SaljareSkapaAnnonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saljare/mina-annonser': {
      id: '/saljare/mina-annonser'
      path: '/saljare/mina-annonser'
      fullPath: '/saljare/mina-annonser'
      preLoaderRoute: typeof SaljareMinaAnnonserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saljare/intressenter': {
      id: '/saljare/intressenter'
      path: '/saljare/intressenter'
      fullPath: '/saljare/intressenter'
      preLoaderRoute: typeof SaljareIntressenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saljare/annons-inskickad': {
      id: '/saljare/annons-inskickad'
      path: '/saljare/annons-inskickad'
      fullPath: '/saljare/annons-inskickad'
      preLoaderRoute: typeof SaljareAnnonsInskickadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saljare/affarer': {
      id: '/saljare/affarer'
      path: '/saljare/affarer'
      fullPath: '/saljare/affarer'
      preLoaderRoute: typeof SaljareAffarerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopare/profil': {
      id: '/kopare/profil'
      path: '/kopare/profil'
      fullPath: '/kopare/profil'
      preLoaderRoute: typeof KopareProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopare/jamfor': {
      id: '/kopare/jamfor'
      path: '/kopare/jamfor'
      fullPath: '/kopare/jamfor'
      preLoaderRoute: typeof KopareJamforRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopare/favoriter': {
      id: '/kopare/favoriter'
      path: '/kopare/favoriter'
      fullPath: '/kopare/favoriter'
      preLoaderRoute: typeof KopareFavoriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopare/bevakningar': {
      id: '/kopare/bevakningar'
      path: '/kopare/bevakningar'
      fullPath: '/kopare/bevakningar'
      preLoaderRoute: typeof KopareBevakningarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kopare/affarer': {
      id: '/kopare/affarer'
      path: '/kopare/affarer'
      fullPath: '/kopare/affarer'
      preLoaderRoute: typeof KopareAffarerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/george/hyresvard': {
      id: '/george/hyresvard'
      path: '/george/hyresvard'
      fullPath: '/george/hyresvard'
      preLoaderRoute: typeof GeorgeHyresvardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/george/fakturor': {
      id: '/george/fakturor'
      path: '/george/fakturor'
      fullPath: '/george/fakturor'
      preLoaderRoute: typeof GeorgeFakturorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/george/anvandare': {
      id: '/george/anvandare'
      path: '/george/anvandare'
      fullPath: '/george/anvandare'
      preLoaderRoute: typeof GeorgeAnvandareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/george/annonser': {
      id: '/george/annonser'
      path: '/george/annonser'
      fullPath: '/george/annonser'
      preLoaderRoute: typeof GeorgeAnnonserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/george/affarer': {
      id: '/george/affarer'
      path: '/george/affarer'
      fullPath: '/george/affarer'
      preLoaderRoute: typeof GeorgeAffarerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annons/$id': {
      id: '/annons/$id'
      path: '/annons/$id'
      fullPath: '/annons/$id'
      preLoaderRoute: typeof AnnonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affar/$id': {
      id: '/affar/$id'
      path: '/affar/$id'
      fullPath: '/affar/$id'
      preLoaderRoute: typeof AffarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/george/annonser/': {
      id: '/george/annonser/'
      path: '/'
      fullPath: '/george/annonser/'
      preLoaderRoute: typeof GeorgeAnnonserIndexRouteImport
      parentRoute: typeof GeorgeAnnonserRoute
    }
    '/saljare/annons/$id': {
      id: '/saljare/annons/$id'
      path: '/saljare/annons/$id'
      fullPath: '/saljare/annons/$id'
      preLoaderRoute: typeof SaljareAnnonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/george/annonser/$id': {
      id: '/george/annonser/$id'
      path: '/$id'
      fullPath: '/george/annonser/$id'
      preLoaderRoute: typeof GeorgeAnnonserIdRouteImport
      parentRoute: typeof GeorgeAnnonserRoute
    }
    '/george/annons-flode/$id': {
      id: '/george/annons-flode/$id'
      path: '/george/annons-flode/$id'
      fullPath: '/george/annons-flode/$id'
      preLoaderRoute: typeof GeorgeAnnonsFlodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annons/$id/intresse': {
      id: '/annons/$id/intresse'
      path: '/intresse'
      fullPath: '/annons/$id/intresse'
      preLoaderRoute: typeof AnnonsIdIntresseRouteImport
      parentRoute: typeof AnnonsIdRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnnonsIdRouteChildren {
  AnnonsIdIntresseRoute: typeof AnnonsIdIntresseRoute
}

const AnnonsIdRouteChildren: AnnonsIdRouteChildren = {
  AnnonsIdIntresseRoute: AnnonsIdIntresseRoute,
}

const AnnonsIdRouteWithChildren = AnnonsIdRoute._addFileChildren(
  AnnonsIdRouteChildren,
)

interface GeorgeAnnonserRouteChildren {
  GeorgeAnnonserIdRoute: typeof GeorgeAnnonserIdRoute
  GeorgeAnnonserIndexRoute: typeof GeorgeAnnonserIndexRoute
}

const GeorgeAnnonserRouteChildren: GeorgeAnnonserRouteChildren = {
  GeorgeAnnonserIdRoute: GeorgeAnnonserIdRoute,
  GeorgeAnnonserIndexRoute: GeorgeAnnonserIndexRoute,
}

const GeorgeAnnonserRouteWithChildren = GeorgeAnnonserRoute._addFileChildren(
  GeorgeAnnonserRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  HurDetFunkarRoute: HurDetFunkarRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  KontaktRoute: KontaktRoute,
  LoggaInRoute: LoggaInRoute,
  LokalerRoute: LokalerRoute,
  McpRoute: McpRoute,
  OmOssRoute: OmOssRoute,
  OnboardingRoute: OnboardingRoute,
  OversiktRoute: OversiktRoute,
  RegistreraRoute: RegistreraRoute,
  TillaggstjansterRoute: TillaggstjansterRoute,
  VillkorRoute: VillkorRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AffarIdRoute: AffarIdRoute,
  AnnonsIdRoute: AnnonsIdRouteWithChildren,
  GeorgeAffarerRoute: GeorgeAffarerRoute,
  GeorgeAnnonserRoute: GeorgeAnnonserRouteWithChildren,
  GeorgeAnvandareRoute: GeorgeAnvandareRoute,
  GeorgeFakturorRoute: GeorgeFakturorRoute,
  GeorgeHyresvardRoute: GeorgeHyresvardRoute,
  KopareAffarerRoute: KopareAffarerRoute,
  KopareBevakningarRoute: KopareBevakningarRoute,
  KopareFavoriterRoute: KopareFavoriterRoute,
  KopareJamforRoute: KopareJamforRoute,
  KopareProfilRoute: KopareProfilRoute,
  SaljareAffarerRoute: SaljareAffarerRoute,
  SaljareAnnonsInskickadRoute: SaljareAnnonsInskickadRoute,
  SaljareIntressenterRoute: SaljareIntressenterRoute,
  SaljareMinaAnnonserRoute: SaljareMinaAnnonserRoute,
  SaljareSkapaAnnonsRoute: SaljareSkapaAnnonsRoute,
  GeorgeIndexRoute: GeorgeIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  GeorgeAnnonsFlodeIdRoute: GeorgeAnnonsFlodeIdRoute,
  SaljareAnnonsIdRoute: SaljareAnnonsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
